### PR TITLE
Goulash.

### PR DESCRIPTION
**Pull request by felixkasza**
My first pull request. I note that with conflicts, git sucks even worse than normally.

### CODE REVIEW

**Comment by aloria** [comment]
Thanks! I'll add this to the queue. :)

**Comment by felixkasza** [comment]
Obviously, I am from Europe (half Hungarian, half Austrian). I have loads of grandma recipes, and just about all of them easier to explain that meat selectionfor goulash. :) No to mention that grandma was a world-class pastry cook. If you are interested, I'll write up more of her recipes. Are you? I mean, I don't want to look as if I were making myself at home instead of behaving like a guest on your blog.

**Comment by aloria** [comment]
Scheduled for tomorrow. Let me know if you have a twitter or other handle I should use to credit you with!

**Comment by felixkasza** [comment]
> Let me know if you have a twitter or other handle I should use to credit you with!

I regret to say that my presence on social media is limited to E-Mail and Signal. I have been doing computer security since before that was a thing, and the old joke applies in full: “I know I am paranoid, but am I paranoid _enough_?” Oh, and getting credit is not my thing either. But thanks!

**Comment by aloria** [comment]
No worries! When I tweet this tomorrow I will credit this to "an anonymous benefactor." 😜

**Comment by aloria** [comment]
Posted! Let me know if I need to fix anything. https://just-the.recipes/2021/08/18/goulash-the-real-thing

**Comment by felixkasza** [comment]
Thanks!

 �

And this is terribly embarrassing, and I swear I read the text a gazillion times, but there is one spot where I typed “if” instead of “it”. The worst part is the typo’s location: First line of the text, second word. <cringe>

 �

Learned if from my late (100  % Hungarian) grandma.

 �

Should I set up another one of those pull request things before I go kill myself?

 �

If I were a politician, this wouldn’t even be noticed, not to mention that as a pol, I would have no shame anyway; but I am supposed to be detail-oriented. “Embarrassing” is hardly sufficient, and I apologise for staining your blog’s rep :(

 �

Oy vey.

 �

Felix.

 �

 �

**Comment by aloria** [comment]
No worries! I just fixed it.

**Comment by felixkasza** [comment]
Thanks! And I really am sorry.

  

Felix.

**Comment by GitHubb3R** [comment]
I do not mean to intrude, but as a Hungarian I'm really fond of all kinds of pörkölt, and must comment on the preparation steps :)

I think that the braising in preparation 7. and 8. with the pre-added paprika powder is a somewhat dangerous, since it may burn easily during the process and will taste bitter. AFAIK the best practice for this is to add paprika after these steps. This also means that additional water comes later too.

Its your submission though, and these are just my 2 cents, which you have all rights to ignore ;)

**Comment by felixkasza** [comment]
Jonapot kiwanok, András!

Thank you for your comment! First off, I am happy that you didn’t vehemently disagree with the recipe overall. In Austria there are dozens of variations on pörkölt, and that’s before we even go into the named variants, of which I listed a few in the posting; I was concerned that someone would respond with “No, that's only done in Pest, the real thing is different!” or something like that. :)

On the substance of the matter, I agree: one has to be very careful roasting the paprika powder. But according to grandma, it is necessary for it imparts some kind of mystical roastedness to the paprika; and it is much harder to ruin the paprika, which at this point already has water in it to prevent it from going over 100 °C than it is to ruin the onions by inavertently browning them.

That said, I'll see if I can figure out how to send aloria another pull request, with a suitable comment noting your concern and suggestion. In case I manage it (git is a steaming pile of —, I want to go back to Perforce!): Do you prefer anonymity or may I credit you?

Szervusz,

Felix.

P.S.: The change will take a week or so; if I bother aloria with another pull request, I might as well write up another recipe. I am thinking of gestenyepüré and some of the delicious things it goes into, like gestzenye torta. But who still has gesztenye trees in his garden? Or I could complement the pörkölt with a paprikás csirke, what do you think? (Grandmas recipe for that also requires lightly braising the chicken in the paprika mix, and her meat selection also is non-standard in that she only ever used chicken breast. Acceptable?)

**Comment by GitHubb3R** [comment]
Kedves Felix!

Sorry for the late reply, GitHub is tied to my work email, and I was on leave.

There really is no need to credit me. The recipe was otherwise excellent and very detailed, there was no need to vehemently disagree. Besides there is a lot of variety to this recipe, depending on whom you talk to. I only commented, because when I was younger I badly ruined a pörkölt with burning the paprika (oc. I did not "extinguish" with water before), and that was a lesson well learned. Also I may never have commented at all, if I did not check in here to see, if anyone has submitted pörkölt yet :D

I also agree that git requires a different mindset, than anything I've ever used before, though I cannot comment on Perforce.

I think both submissions are fine, my wife also prefers chicken breast, but I disagree with her in that matter :)

As for gesztenye, I agree that very few peple have these trees at home, but there is a deep fried variety of the puree available in most grocery stores. But IDK if that even counts, since it takes away most of the fun :)

Best regards,
András

**Pull request merged**
