### PR TITLE
I forgot to update all the references to main branch

### PR DESCRIPTION
**Pull request by teancom**
Sorry about that!

### CODE REVIEW

**Comment by teancom** [comment]
@aloria Just checking if there was a reason to not merge this?

**Comment by aloria** [comment]
@teancom they were automatically fixed by the next Jekyll rebuild :)

**Comment by teancom** [comment]
I still see them in `HEAD` of `main`?

```
$ rg -i master
README.md
12:If you're comfortable with Git, you can [submit a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). Recipe posts are in [aloria.github.io/_posts](https://github.com/aloria/aloria.github.io/tree/master/_posts), which you can use as a starting template. Posts use [Jekyll Markdown](https://gist.github.com/roachhd/779fa77e9b90fe945b0c).

_layouts/index0.html
91:      <a href="https://github.com/aloria/aloria.github.io/blob/master/README.md" target="_blank">Submit</a>

_layouts/index.html
91:      <a href="https://github.com/aloria/aloria.github.io/blob/master/README.md" target="_blank">Submit</a>

_includes/header.html
19:      <a href="https://github.com/aloria/aloria.github.io/blob/master/README.md" target="_blank">Submit</a>
```

**Comment by teancom** [comment]
Sorry, I'm not super Jekyll savvy, so I'm probably missing something obvious. :-/

**Comment by aloria** [comment]
Oooh, you're right. I guess github redirects main to master. Whoops.

**Pull request merged**
